### ISSUE TITLE
Okno startowe dla pracownika (po zalogowaniu)

### ISSUE THREAD

**Issue by jacek010** [jacek010/BD2_MoThor_demo#3]

**Comment by jacek010** [comment]
Bartek, jakbyś mógł, to dodaj jeszcze (bez oprogramowania ich) dwa przyciski:
- widok listy pracowników
- widok listy samochodów

Bo wtedy będzie można równolegle robić ich działanie bez konfliktów w kodzie

**Comment by Creation2012** [comment]
Trochę w innej formię będę to robić, bo jak pisałem na tabach.
Na ten moment, jest zrobiony model w javafx z:

- widoku listy klientów
- widoku listy samochodów
- **widoku listy pracowników**

Co do tego ostatniego, to trzeba będzie to ograniczyć dla konkretnego poziomu konta, że tylko manager to widzi.

Dodatkowo można zamknąć #4, zrobiłem to już w tym jednym branchu. Nie ma co rozdrabniać.
Ogólnie pojawiają mi się już tu pewne nieścisłości, ale to później prawdopodobnie będzie trzeba pozmieniać - bo nie wiem do końca czy można dzielić panel w javafx na kontrolery - że 3 taby mają 3 różne kontrolery, czy kontroler jest na cały panel (ze wszystkimi tabami), jeśli to drugie to całe nazewnictwo przydałoby się zmienić, jak na razie zrobiłem, że 3 taby - 3 różne, ale z tego co patrzę to raczej nie.
